Repository CodeURJC-DAW-2022-23/webapp9, pull requests merged in 2023-03, with the labels that each got.

#47 Load images on pages and include images in Itineraries
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/DestinationWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/DetailsController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/ItineraryWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/PlaceWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/Destination.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/Information.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/Itinerary.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/DatabaseInitializer.java
  TripScanner/src/main/resources/templates/details.html
Labels: feature

#58 Views usage
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/DestinationWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/DetailsController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/ItineraryWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/PlaceWebController.java
Labels: feature

#59 Dev admin
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/DestinationWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/DetailsController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/HeaderController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/ItineraryWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/ManagementController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/PlaceWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/UserWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/Destination.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/Itinerary.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/Place.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/User.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/repository/ReviewRepository.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/repository/UserRepository.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/DatabaseInitializer.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/ReviewService.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/UserService.java
  TripScanner/src/main/resources/templates/addEditItem.html
  TripScanner/src/main/resources/templates/management.html
Labels: feature

#66 User itineraries
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/DetailsController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/ItineraryWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/ProfileController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/Itinerary.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/security/WebSecurityConfig.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/utils/EmailService.java
  TripScanner/src/main/resources/templates/details.html
  TripScanner/src/main/resources/templates/editItinerary.html
  TripScanner/src/main/resources/templates/error/400.html
  TripScanner/src/main/resources/templates/error/405.html
  TripScanner/src/main/resources/templates/myItineraries.html
  TripScanner/src/main/resources/templates/profile.html
Labels: feature

#73 Graph
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/HomeController.java
  TripScanner/src/main/resources/templates/header.html
  TripScanner/src/main/resources/templates/index.html
Labels: feature

#78 Feature: Itineraries can now be private or public
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/DetailsController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/HeaderController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/ItineraryWebController.java
  TripScanner/src/main/resources/templates/addEditItem.html
  TripScanner/src/main/resources/templates/editItinerary.html
  TripScanner/src/main/resources/templates/header.html
  TripScanner/src/main/resources/templates/myItineraries.html
Labels: feature

#82 Bugs
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/DetailsController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/HomeController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/ProfileController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/repository/ItineraryRepository.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/DatabaseInitializer.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/ItineraryService.java
  TripScanner/src/main/resources/static/css/style.css
  TripScanner/src/main/resources/templates/details.html
  TripScanner/src/main/resources/templates/detailsInformation.html
  TripScanner/src/main/resources/templates/footer.html
  TripScanner/src/main/resources/templates/index.html
  TripScanner/src/main/resources/templates/login.html
  TripScanner/src/main/resources/templates/profile.html
  TripScanner/src/main/resources/templates/search.html
  TripScanner/src/main/resources/templates/sign.html
Labels: bug, enhancement

#84 Code format style
  TripScanner/.idea/compiler.xml
  TripScanner/pom.xml
  TripScanner/src/main/java/com/tripscanner/TripScanner/TripScannerApplication.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/DestinationWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/DetailsController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/HeaderController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/HomeController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/ItineraryWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/ManagementController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/PlaceWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/ProfileController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/ReviewWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/SearchController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/SignController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/UserWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/Itinerary.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/User.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/repository/DestinationRepository.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/repository/ItineraryRepository.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/repository/PlaceRepository.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/repository/ReviewRepository.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/security/CSRFHandlerConfiguration.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/security/WebSecurityConfig.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/UserService.java
  TripScanner/src/main/resources/static/css/signUp.css
  TripScanner/src/main/resources/static/css/styleLogIn.css
  TripScanner/src/main/resources/static/js/details.js
  TripScanner/src/main/resources/static/js/search.js
  TripScanner/src/main/resources/templates/addEditItem.html
  TripScanner/src/main/resources/templates/detailsReview.html
  TripScanner/src/main/resources/templates/editItinerary.html
  TripScanner/src/main/resources/templates/error/400.html
  TripScanner/src/main/resources/templates/error/403.html
  TripScanner/src/main/resources/templates/error/404.html
  TripScanner/src/main/resources/templates/error/405.html
  TripScanner/src/main/resources/templates/error/500.html
  TripScanner/src/main/resources/templates/error/error.html
  TripScanner/src/main/resources/templates/header.html
  TripScanner/src/main/resources/templates/login.html
  TripScanner/src/main/resources/templates/management.html
  TripScanner/src/main/resources/templates/myItineraries.html
  TripScanner/src/main/resources/templates/profile.html
  TripScanner/src/main/resources/templates/search.html
  TripScanner/src/main/resources/templates/searchResult.html
Labels: enhancement

#108 Rest security
  TripScanner/pom.xml
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/RestLoginController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/DestinationWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/DetailsController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/HeaderController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/HomeController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/ItineraryWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/ManagementController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/PlaceWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/ProfileController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/ReviewWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/SearchController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/SignController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/UserAccountControler.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/UserWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/security/jwt/AuthResponse.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/security/jwt/JwtCookieManager.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/security/jwt/JwtRequestFilter.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/security/jwt/JwtTokenProvider.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/security/jwt/LoginRequest.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/security/jwt/SecurityCipher.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/security/jwt/Token.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/security/jwt/UserLoginService.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/security/restSecurity/RestSecurityConfig.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/security/webSecurity/CSRFHandlerConfiguration.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/security/webSecurity/WebSecurityConfig.java
  TripScanner/src/main/resources/application.properties
Labels: feature, api rest

#113 Auxiliary services methods for getting related information
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/DetailsController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/repository/DestinationRepository.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/repository/ItineraryRepository.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/repository/PlaceRepository.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/repository/ReviewRepository.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/repository/UserRepository.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/DestinationService.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/ItineraryService.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/PlaceService.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/ReviewService.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/UserService.java
Labels: enhancement

#112 JSON handling for current models
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/Destination.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/Itinerary.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/Place.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/Review.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/User.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/DestinationDetails.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/ItineraryDetails.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/PlaceDetails.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/UserDetails.java
Labels: feature

#117 Fix readme styling
  README.md
Labels: documentation

#116 110 fix add place to private itinerary
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/HomeController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/repository/ItineraryRepository.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/ItineraryService.java
  TripScanner/src/main/resources/templates/addEditItem.html
  TripScanner/src/main/resources/templates/details.html
  TripScanner/src/main/resources/templates/detailsInformation.html
  TripScanner/src/main/resources/templates/detailsReview.html
  TripScanner/src/main/resources/templates/editItinerary.html
  TripScanner/src/main/resources/templates/myItineraries.html
  TripScanner/src/main/resources/templates/profile.html
Labels: bug

#114 Unregistered users functionality
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/DestinationRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/IndexRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/ItineraryRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/PlaceRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/UserRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/User.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/IndexDetails.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/UserDTO.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/repository/ItineraryRepository.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/ItineraryService.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/UserService.java
Labels: feature, api rest

#121 Dev api admin places users
  README.md
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/DestinationRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/IndexRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/ItineraryRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/PlaceManagementRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/PlaceRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/UserManagementRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/UserRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/HomeController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/UserWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/User.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/IndexDetails.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/PlaceDTO.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/UserDTO.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/repository/ItineraryRepository.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/security/restSecurity/RestSecurityConfig.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/ItineraryService.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/UserService.java
  TripScanner/src/main/resources/templates/addEditItem.html
  TripScanner/src/main/resources/templates/details.html
  TripScanner/src/main/resources/templates/detailsInformation.html
  TripScanner/src/main/resources/templates/detailsReview.html
  TripScanner/src/main/resources/templates/editItinerary.html
  TripScanner/src/main/resources/templates/myItineraries.html
  TripScanner/src/main/resources/templates/profile.html
Labels: feature, api rest

#119 Api admin
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/DestinationManagementRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/ItineraryManagementRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/PlaceManagementRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/UserManagementRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/UserWebController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/Itinerary.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/ItineraryDTO.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/PlaceDTO.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/UserDTO.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/repository/DestinationRepository.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/repository/PlaceRepository.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/security/restSecurity/RestSecurityConfig.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/DestinationService.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/UserService.java
  TripScanner/src/main/resources/application.properties
  destination.postman_collection.json
Labels: feature, api rest

#125 Fix: Empty DTO constructors
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/PlaceDTO.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/UserDTO.java
Labels: bug

#130 Extract Graph to its controller
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/GraphsRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/IndexRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/GraphDetails.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/IndexDetails.java
Labels: enhancement, api rest

#134 89 registered user documentation api rest
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/ItineraryRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/RestLoginController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/UserRestController.java
Labels: documentation, api rest

#133 Increment views on item's requests
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/DestinationRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/ItineraryRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/PlaceRestController.java
Labels: bug, api rest

#128 Docs: API Places and Users Management documentation
  TripScanner/pom.xml
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/PlaceManagementRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/UserManagementRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/UserDTO.java
Labels: documentation, api rest

#132 Admin destinations itinerary docs
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/DestinationManagementRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/ItineraryManagementRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/DatabaseInitializer.java
  TripScanner/src/main/resources/img-samples/Ajya-Sofiya.jpeg
  TripScanner/src/main/resources/img-samples/Beijing.jpeg
  TripScanner/src/main/resources/img-samples/Cathedral-of-Christ-the-Savior.jpeg
  TripScanner/src/main/resources/img-samples/Colosseum-Rome.jpeg
  TripScanner/src/main/resources/img-samples/blue-mosque.jpeg
  TripScanner/src/main/resources/img-samples/fontain.jpeg
  TripScanner/src/main/resources/img-samples/forbidden-city.jpeg
  TripScanner/src/main/resources/img-samples/grand-bazaar.jpeg
  TripScanner/src/main/resources/img-samples/istanbul.jpeg
  TripScanner/src/main/resources/img-samples/izmaylovskiy-kreml.jpeg
  TripScanner/src/main/resources/img-samples/panteon.jpeg
  TripScanner/src/main/resources/img-samples/roma.jpeg
  TripScanner/src/main/resources/img-samples/roman-forum.jpeg
  TripScanner/src/main/resources/img-samples/tienanmen.jpeg
Labels: documentation, api rest

#135 API Documentation
  TripScanner/pom.xml
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/DestinationManagementRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/DestinationRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/GraphsRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/ItineraryManagementRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/ItineraryRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/PlaceManagementRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/PlaceRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/RestLoginController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/UserManagementRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/UserRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/UserDTO.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/service/DatabaseInitializer.java
  TripScanner/src/main/resources/img-samples/Ajya-Sofiya.jpeg
  TripScanner/src/main/resources/img-samples/Beijing.jpeg
  TripScanner/src/main/resources/img-samples/Cathedral-of-Christ-the-Savior.jpeg
  TripScanner/src/main/resources/img-samples/Colosseum-Rome.jpeg
  TripScanner/src/main/resources/img-samples/blue-mosque.jpeg
  TripScanner/src/main/resources/img-samples/fontain.jpeg
  TripScanner/src/main/resources/img-samples/forbidden-city.jpeg
  TripScanner/src/main/resources/img-samples/grand-bazaar.jpeg
  TripScanner/src/main/resources/img-samples/istanbul.jpeg
  TripScanner/src/main/resources/img-samples/izmaylovskiy-kreml.jpeg
  TripScanner/src/main/resources/img-samples/panteon.jpeg
  TripScanner/src/main/resources/img-samples/roma.jpeg
  TripScanner/src/main/resources/img-samples/roman-forum.jpeg
  TripScanner/src/main/resources/img-samples/tienanmen.jpeg
Labels: documentation, api rest

#122 Docker
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/webController/DetailsController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/utils/PdfGenerator.java
  TripScanner/src/main/resources/application.properties
  docker/Dockerfile
  docker/create_image.sh
  docker/docker-compose.yml
Labels: feature, docker

#139 Rest reviews
  TripScanner/src/main/java/com/tripscanner/TripScanner/controller/restController/ItineraryRestController.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/ItineraryDetailsDTO.java
  TripScanner/src/main/java/com/tripscanner/TripScanner/model/rest/ReviewDTO.java
Labels: documentation, feature, api rest
